export const STATUS_CODES: {
  [key: string]: { official: boolean; description: string; redirect?: true };
} = {
  "100": { official: true, description: "Continue" },
  "101": { official: true, description: "Switching Protocols" },
  "102": { official: true, description: "Processing" },
  "103": { official: true, description: "Early Hints" },
  "200": { official: true, description: "OK" },
  "201": { official: true, description: "Created" },
  "202": { official: true, description: "Accepted" },
  "203": { official: true, description: "Non-Authoritative Information" },
  "204": { official: true, description: "No Content" },
  "205": { official: true, description: "Reset Content" },
  "206": { official: true, description: "Partial Content" },
  "207": { official: true, description: "Multi-Status" },
  "208": { official: true, description: "Already Reported" },
  "226": { official: true, description: "IM Used" },
  "300": { official: true, description: "Multiple Choices" },
  "301": { official: true, description: "Moved Permanently", redirect: true },
  "302": { official: true, description: "Found", redirect: true },
  "303": { official: true, description: "See Other", redirect: true },
  "304": { official: true, description: "Not Modified" },
  "305": { official: true, description: "Use Proxy", redirect: true },
  "306": { official: true, description: "Switch Proxy" },
  "307": { official: true, description: "Temporary Redirect", redirect: true },
  "308": { official: true, description: "Permanent Redirect", redirect: true },
  "400": { official: true, description: "Bad Request" },
  "401": { official: true, description: "Unauthorized" },
  "402": { official: true, description: "Payment Required" },
  "403": { official: true, description: "Forbidden" },
  "404": { official: true, description: "Not Found" },
  "405": { official: true, description: "Method Not Allowed" },
  "406": { official: true, description: "Not Acceptable" },
  "407": { official: true, description: "Proxy Authentication Required" },
  "408": { official: true, description: "Request Timeout" },
  "409": { official: true, description: "Conflict" },
  "410": { official: true, description: "Gone" },
  "411": { official: true, description: "Length Required" },
  "412": { official: true, description: "Precondition Failed" },
  "413": { official: true, description: "Payload Too Large" },
  "414": { official: true, description: "URI Too Long" },
  "415": { official: true, description: "Unsupported Media Type" },
  "416": { official: true, description: "Range Not Satisfiable" },
  "417": { official: true, description: "Expectation Failed" },
  "418": { official: true, description: "I'm a teapot" },
  "421": { official: true, description: "Misdirected Request" },
  "422": { official: true, description: "Unprocessable Content" },
  "423": { official: true, description: "Locked" },
  "424": { official: true, description: "Failed Dependency" },
  "425": { official: true, description: "Too Early" },
  "426": { official: true, description: "Upgrade Required" },
  "428": { official: true, description: "Precondition Required" },
  "429": { official: true, description: "Too Many Requests" },
  "431": { official: true, description: "Request Header Fields Too Large" },
  "451": { official: true, description: "Unavailable For Legal Reasons" },
  "500": { official: true, description: "Internal Server Error" },
  "501": { official: true, description: "Not Implemented" },
  "502": { official: true, description: "Bad Gateway" },
  "503": { official: true, description: "Service Unavailable" },
  "504": { official: true, description: "Gateway Timeout" },
  "505": { official: true, description: "HTTP Version Not Supported" },
  "506": { official: true, description: "Variant Also Negotiates" },
  "507": { official: true, description: "Insufficient Storage" },
  "508": { official: true, description: "Loop Detected" },
  "510": { official: true, description: "Not Extended" },
  "511": { official: true, description: "Network Authentication Required" },
  // Unofficial
  "598": {
    official: false,
    description: "(Informal convention) Network read timeout error",
  },
  "599": { official: false, description: "Network Connect Timeout Error" },
  // nginx
  "444": { official: false, description: "No Response" },
  "494": { official: false, description: "Request header too large" },
  "495": { official: false, description: "SSL Certificate Error" },
  "496": { official: false, description: "SSL Certificate Required" },
  "497": { official: false, description: "HTTP Request Sent to HTTPS Port" },
  "499": { official: false, description: "Client Closed Request" },
  // Apache
  "218": { official: false, description: "This is fine" },
  "509": { official: false, description: "Bandwidth Limit Exceeded" },
  // IIS
  "440": { official: false, description: "Login Time-out" },
  "449": { official: false, description: "Retry With" },
  // "451": { official: false, description: "Redirect" },
  // Cloudflare
  "520": {
    official: false,
    description: "Web Server Returned an Unknown Error",
  },
  "521": { official: false, description: "Web Server Is Down" },
  "522": { official: false, description: "Connection Timed Out" },
  "523": { official: false, description: "Origin Is Unreachable" },
  "524": { official: false, description: "A Timeout Occurred" },
  "525": { official: false, description: "SSL Handshake Failed" },
  "526": { official: false, description: "Invalid SSL Certificate" },
  "527": { official: false, description: "Railgun Error" },
  // "530": { official: false, description: "" },
  // AWS Elastic Load Balancing
  "000": { official: false, description: "" },
  "460": { official: false, description: "" },
  "463": { official: false, description: "" },
  "464": { official: false, description: "" },
  "561": { official: false, description: "" },
  // Spring
  // "420": { official: false, description: "Method Failure" },
  // Microsoft
  "450": {
    official: false,
    description: "Blocked by Windows Parental Controls",
  },
  // Shopify
  "430": { official: false, description: "Request Header Fields Too Large" },
  // "430": { official: false, description: "Shopify Security Rejection" },
  "530": { official: false, description: "Origin DNS Error" },
  "540": { official: false, description: "Temporarily Disabled" },
  "783": { official: false, description: "Unexpected Token" },
  // Twitter
  "420": { official: false, description: "Enhance Your Calm" },
  // Laravel
  "419": { official: false, description: "Page Expired" },
  // Esri
  "498": { official: false, description: "Invalid Token" },
  // "499": { official: false, description: "Token Required" },
  // Pantheon Systems
  // "530": { official: false, description: "Site is frozen" },
  // Qualys
  "529": { official: false, description: "Site is overloaded" },
};
